### ISSUE TITLE
Major bug

### ISSUE THREAD

**Issue by Zolcman2** [groupoid/anders#1]
The following code passes type checking:

```
module false where

import lib/foundations/univalent/iso

option pre-eval false

def rec₂ (A : U) (a b : A) : 𝟐 → A := 
    ind₂ (λ (_ : 𝟐), A) a b

def not := 
    rec₂ 𝟐 1₂ 0₂

def not-not := 
    ind₂ (λ (x : 𝟐), Path 𝟐 (not (not x)) x) (<_> 0₂) (<_> 1₂)

def boolEqBool := 
    isoPath 𝟐 𝟐 not not not-not not-not

def T : Path 𝟐 (idfun″ 𝟐 (idfun″ 𝟐 1₂)) 0₂ :=
    <i> transp (<j> hcomp U (-i ∨ i ∨ -j ∨ j)
                    (λ (k : I), [(i = 0) → boolEqBool @ (k ∧ j), (i = 1) 
                                    → 𝟐, (j = 0) → 𝟐, (j = 1) → 𝟐]) 𝟐) 0 0₂

def G (x : 𝟐) : Path 𝟐 (idfun″ 𝟐 x) x :=
    <i> (idfun=idfun″ 𝟐 @ -i) x

def R : Path 𝟐 0₂ 1₂ :=
    kan 𝟐 (idfun″ 𝟐 (idfun″ 𝟐 1₂)) (idfun″ 𝟐 1₂) 0₂ 1₂ T (G 1₂) (G (idfun″ 𝟐 1₂))

def f : 𝟐 → U := 
    ind₂ (λ (_ : 𝟐), U) 𝟏 𝟎

def g : 𝟎 := 
    subst 𝟐 f 0₂ 1₂ R ★
```

when it shouldn't.

Curiously awaiting a fix!

**Comment by 5HT** [comment]
коля, ты пизданулся, надо было работать, когда тебе платили бабки, счас уже поздно иди на пары в свою шарашку
тебя ждет судьба Ромы Михайлова

**Comment by Zolcman2** [comment]
What are you talking about? 

I am the author of the [issue about your theft of the hx code](https://github.com/krpors/hx/issues/22).
Unfortunately for me, you blocked my main account, so I had to register another one.

And I am not one of the three people you listed. 

Also, let's speak in English from now on.

**Comment by 5HT** [comment]
Хуй будешь?

**Comment by Zolcman2** [comment]
All I ask is to fix the problem above, which is objectively present in the Anders repository you hijacked.

And even don't try to copy code from the [real author's repository](github.com/forked-from-1kasper/anders/), I detailed the possible consequences [in my message from "hx" issue](https://github.com/krpors/hx/issues/22#issuecomment-1156911716).
